### ISSUE TITLE
Back of card with horizontal rotation shows mirrored and upside down.

### ISSUE THREAD

**Issue by angelolucas** [lhandel/react-native-card-flip#4]
Back of card with `flipDirection="x"` shows mirrored and upside down.

Example:
![issue](https://user-images.githubusercontent.com/828776/45714932-611c3980-bb69-11e8-8bbd-b351972afb61.gif)

**Comment by TntManiak** [comment]
Hello,

Did you found any solutions about this? 
I've a strange similar issue. I've a <CardFlip> with inside 2 touchableOpacity. When I touch these, the card flip correctly.
However, if I flip the card from a component outside of <CardFlip>, it just mirror de actual card instead of showing his back card.

**Comment by TntManiak** [comment]
By digging into the code of CardFlip.js, I ended up to find what caused my issue.
In `flipY()` and `flipX()` method, you need to call `this._flipTo()` BEFORE the setState as you need to flip before the states are updated.

Do you want me to do a PR?

**Comment by lhandel** [comment]
This problem should be fixed in the last update :)

**Comment by ramuachala** [comment]
i needed to flip based on props.. the below works but for some reason the animation is very slow
```
 componentDidMount() {
    if (this.props.global.side === "back") {
    
        this.card.flip();

    }
```

then when i try this, it flips and mirrors
```
 componentDidMount() {
    if (this.props.global.side === "back") {
         requestAnimationFrame(() => {
        this.card.flip();
      });
    }

```
